import {Person} from "./person";

export const PERSON_EXAMPLE_DATA: Person[] = [
  {
    id: 1,
    name: 'Juan',
    lastName: 'Pérez',
    document: {
      id: 1,
      type: 'DNI',
      number: '12345678A',
      description: 'Documento Nacional de Identidad',
    },
    city: {
      id: 1,
      name: 'Madrid',
      state: 'Comunidad de Madrid',
      country: 'España',
      description: 'Capital de España',
    },
    birthDate: '1990-01-01T05:00:00.000+00:00',
    email: 'juan.perez@example.com',
    phone: '123456789',
    username: 'jperez',
    password: 'password123',
  },
  {
    id: 2,
    name: 'María',
    lastName: 'López',
    document: {
      id: 2,
      type: 'Pasaporte',
      number: 'A1234567',
      description: 'Pasaporte Español',
    },
    city: {
      id: 2,
      name: 'Barcelona',
      state: 'Cataluña',
      country: 'España',
      description: 'Ciudad conocida por su arte y arquitectura',
    },
    birthDate: '1985-05-15T05:00:00.000+00:00',
    email: 'maria.lopez@example.com',
    phone: '987654321',
    username: 'mlopez',
    password: 'password456',
  },
  {
    id: 3,
    name: 'Carlos',
    lastName: 'García',
    document: {
      id: 3,
      type: 'CE',
      number: '23456789B',
      description: 'Cédula de Extranjería',
    },
    city: {
      id: 3,
      name: 'Valencia',
      state: 'Comunidad Valenciana',
      country: 'España',
      description: 'Famosa por la Ciudad de las Artes y las Ciencias',
    },
    birthDate: '1995-09-30T05:00:00.000+00:00',
    email: 'carlos.garcia@example.com',
    phone: '567123890',
    username: 'cgarcia',
    password: 'password789',
  },
  {
    id: 4,
    name: 'Ana',
    lastName: 'Martínez',
    document: {
      id: 1,
      type: 'DNI',
      number: '12345678A',
      description: 'Documento Nacional de Identidad',
    },
    city: {
      id: 4,
      name: 'Paris',
      state: 'Paris',
      country: 'Francia',
      description: 'Capital de Francia y conocida por la Torre Eiffel',
    },
    birthDate: '1988-07-20T05:00:00.000+00:00',
    email: 'ana.martinez@example.com',
    phone: '456789012',
    username: 'amartinez',
    password: 'passwordabc',
  },
  {
    id: 5,
    name: 'Luis',
    lastName: 'Rodríguez',
    document: {
      id: 2,
      type: 'Pasaporte',
      number: 'A1234567',
      description: 'Pasaporte Español',
    },
    city: {
      id: 5,
      name: 'Roma',
      state: 'Roma',
      country: 'Italia',
      description: 'Capital de Italia y hogar del Coliseo Romano',
    },
    birthDate: '1980-03-12T05:00:00.000+00:00',
    email: 'luis.rodriguez@example.com',
    phone: '654321098',
    username: 'lrodriguez',
    password: 'passworddef',
  }
];
